use_default_settings:
  engines:
    keep_only:
      - google
      - bing
      - brave
      - duckduckgo
      - wikipedia

engines:
  - name: google
    disabled: false
  - name: bing
    disabled: false
  - name: brave
    disabled: false
  - name: duckduckgo
    disabled: false
  - name: wikipedia
    disabled: false

general:
  instance_name: "Local SearXNG"

search:
  formats:
    - html
    - json

server:
  bind_address: "0.0.0.0"
  secret_key: "configure-this-in-.env"
  limiter: false
  image_proxy: false

valkey:
  url: "valkey://valkey:6379/0"
